<a href="https://colab.research.google.com/github/MarioViniciusBC/NumPy/blob/main/Mascara_Fancy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Máscaras Booleanas

Em Numpy, quando tratamos de ufuncs verificamos que usar os operadores aritméticos `+`, `-`, `*`, `/` e outros em arrays leva a operações elemento a elemento. O NumPy implementa operadores de comparação como ufuncs elemento a elemento. O resultado desses operadores de comparação é sempre um array com um tipo de dado Booleano. Vejamos um exemplo com um array bidimensional:

In [2]:
import numpy as np

In [5]:
# criando o gerador de números aleatórios com seed 0
rng = np.random.RandomState(0)

# Cria um array bidimensional 3x4 de inteiros aleatórios no intervalo [0, 10)
x = rng.randint(10, size=(3, 4)) # Queremos a resposta no formato size=(3, 4)
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

* **Observação sobre o `RandomState`**: Ele não devolve apenas um tipo de número. Ele possui vários "botões" (métodos) para gerar números de formatos diferentes, dependendo do que precisarmos. Por exemplo, se salvamos o gerador na variável `rng = np.random.RandomState(0)`, podemos pedir a ele:

  * `rng.rand(3)`: "Me dê 3 números decimais entre 0 e 1."

  * `rng.randint(1, 100)`: "Me dê um número inteiro entre 1 e 100."

  * `rng.randn(5)`: "Me dê 5 números que sigam uma distribuição normal (aquela curva de sino da estatística)."

  * `rng.choice(['A', 'B', 'C'])`: "Escolha aleatoriamente um item dessa lista."

Agora, aplicamos uma condição:

In [6]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

por trás dos panos, o computador enxerga o `True` como o número **1** e o `False` como o número **0**.

Então, para o Python, a sua tabela invisível está assim:

* `[1, 1, 1, 1]`

* `[0, 0, 1, 1]`

* `[1, 1, 0, 0]`

o resultado é um array Booleano. Agora, vejamos:

In [7]:
# quantos valores menores que 6?
np.count_nonzero(x < 6)

8

Essa função conta "quantos valores **não são zero**". Olhando para a nossa tabela de 1s e 0s ali em cima, temos exatamente **8** números "1".

podemos fazer o mesmo com `sum()`:

In [8]:
np.sum(x < 6)

np.int64(8)

Essa função simplesmente **soma** todos os valores. Somar todos os 1s e 0s juntos também dá **8**.

O benefício de `sum()` é que, como com outras funções de agregação do NumPy, essa soma pode ser feita ao longo de linhas ou colunas também:

In [9]:
# quantos valores menores que 6 em cada linha?
np.sum(x < 6, axis=1)
# array([4, 2, 2])

array([4, 2, 2])

Agora, vamos usar arrays Booleanos como máscaras, selecionando um subconjunto específico dos próprios dados:

In [10]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

Vamos aplicar a condição:

In [12]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

Agora, para selecionar esses valores do array, podemos simplesmente indexar neste array Booleano. Isso é conhecido como uma operação de **mascaramento**:

In [13]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])

O que é retornado é um array unidimensional preenchido com todos os valores que atendem a essa condição; em outras palavras, todos os valores nas posições em que o array de máscara é `True`.

# Fancy Indexing

A indexação extravagante significa passar um array de índices para acessar múltiplos elementos do array de uma vez.

In [14]:
import numpy as np
rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


Se quisermos acessar os elemntos de índices 2, 3 e 7 podemos passar uma lista com esses valores como exemplificado a seguir:

In [15]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

Ao usar a indexação extravagante, o formato (shape) do resultado reflete o formato dos arrays de índice em vez do formato do array sendo indexado:

In [16]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])