<a href="https://colab.research.google.com/github/MarioViniciusBC/NumPy/blob/main/Numpy_indexing_slicing_assigning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy - Indexing, Slicing e Assigning

In [3]:
import numpy as np

In [2]:
list_3d = [[[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
            [10, 11, 12]],

           [[13, 14, 15],
            [16, 17, 18],
            [19, 20, 21],
            [22, 23, 24]]]
list_3d

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
 [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]]

Na célula acima, foi criada uma lista comum do Python chamada list_3d. Pense nela como uma "lista de listas de listas". Para o Python, a list_3d é literalmente apenas uma caixa guardando outras caixas.

* Ele não sabe e não se importa se isso forma um "retângulo" perfeito de dados.

* Nas listas do Python, você poderia ter a primeira linha com 3 números, a segunda linha com 10 números e a terceira com uma palavra (texto). O Python aceitaria isso tranquilamente, pois ele não exige uma estrutura rígida.

* Ele não tem propriedades matemáticas prontas.

In [4]:
array_3d = np.array(list_3d)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

Os arrays do NumPy são muito mais rápidos e consomem menos memória do que as listas nativas do Python. Além disso, eles permitem fazer cálculos matemáticos complexos de forma muito mais simples.

In [5]:
# shape retorna o tamanho de cada dimensão
array_3d.shape

(2, 4, 3)

* **2:** Representa a primeira dimensão (**profundidade**). Significa que existem 2 grandes blocos de matrizes no seu array.

* **4:** Representa a segunda dimensão (**linhas**). Significa que dentro de cada um desses blocos, existem 4 linhas.

* **3:** Representa a terceira dimensão (**colunas**). Significa que cada linha possui 3 elementos (ou colunas)

## Indexing

A indexação (indexing) é o mecanismo fundamental na programação e na ciência de dados utilizado para localizar, acessar ou modificar elementos específicos dentro de uma estrutura de dados, como uma lista ou uma matriz.

A seguir, alguns exemplos:

In [9]:
array_3d[1]

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [10]:
array_3d[1][0] # é o mesmo que array[1, 0]

array([13, 14, 15])

In [11]:
array_3d[1, 2, 0]

np.int64(19)

In [12]:
array_3d[1][2][0]

np.int64(19)

In [17]:
array_3d[[0, 1]] # Retorna profundidade 0 e profundidade 1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

o comando `array_3d[[0, 1]]` está usando uma lista de números (o `[0, 1]`) dentro dos colchetes principais de seleção. Isso diz ao NumPy que você não quer apenas um único bloco, mas sim uma seleção múltipla e específica deles. Como você pediu os blocos das posições 0 e 1, e sua matriz original é composta por exatamente esses dois blocos, o programa simplesmente retornou a matriz inteira para você, sem esconder nada.

 Agora, e se usarmos `:` na primeira posição do bloco principal de seleção?

In [18]:
array_3d[:, [0, 1]]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18]]])

Quando usamos esses dois-pontos (`:`) sozinhos na primeira posição do comando (que representa a profundidade ou os blocos grandes), estamos dando uma ordem ao NumPy para pegar todos os blocos disponíveis. Ele funciona como um coringa ou um atalho rápido para "selecione tudo o que houver nesta dimensão".

Logo depois dos dois-pontos, temos uma vírgula para avisar ao Python que mudamos de dimensão, seguida novamente por `[0, 1]`. Como agora estamos na segunda posição do comando, essa parte se refere estritamente às linhas que estão dentro dos blocos. Portanto, você está pedindo especificamente a linha 0 (a primeira) e a linha 1 (a segunda).

In [19]:
array_3d[-1]

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

O comando `array_3d[-1]` demonstra o uso da indexação negativa.

* Na sintaxe do Python e do NumPy, índices negativos instruem o interpretador a acessar os elementos em ordem reversa, onde -1 representa o último elemento ao longo do eixo referenciado.

* Como nenhum eixo específico foi explicitamente declarado (através do uso de vírgulas), a operação é aplicada ao eixo de índice 0 (a primeira dimensão, que define a "profundidade" do arranjo).

* Consequentemente, o retorno é a última matriz bidimensional (2D) completa contida na estrutura 3D original.

### Máscaras

O mascaramento é uma das técnicas mais eficientes oferecidas pelo NumPy para a filtragem e extração de subconjuntos de dados. Em vez de iterar sobre os elementos de um arranjo usando laços de repetição tradicionais (como o for do Python), o NumPy utiliza operações vetorizadas otimizadas em baixo nível, garantindo alta performance computacional para grandes volumes de dados.

* Quando você passa uma lista nativa de valores booleanos (como `[True, False]`) como índice para um arranjo multidimensional no NumPy, a biblioteca interpreta isso como um filtro estrutural de eixo, operando por padrão na primeira dimensão (eixo 0, que representa os blocos ou linhas principais).  Diferente do mascaramento condicional (tratado a seguir) que avalia cada número individualmente e achata o resultado, essa técnica exige que o tamanho da lista booleana seja estritamente igual ao número de elementos desse eixo principal; ela atua mantendo integralmente os sub-arranjos nas posições correspondentes a True e descartando por completo os alocados em False, o que tem a grande vantagem de preservar a estrutura geométrica e a dimensionalidade original dos dados filtrados.

Acompanhe o exemplo a seguir:

In [21]:
mask = [True, False]
array_3d[mask]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

As instruções `mask = [True, False]` seguidas de `array_3d[mask]` exemplificam a aplicação de uma máscara booleana direta a um eixo específico.

Neste cenário, a lista booleana atua como um seletor posicional para o eixo 0. O comprimento da máscara deve corresponder ao tamanho da dimensão sendo indexada (neste caso, tamanho 2).

O valor `True` no índice 0 indica que o primeiro bloco de dados deve ser mantido na visualização final, enquanto o valor `False` no índice 1 instrui o NumPy a descartar o segundo bloco. O resultado mantém a dimensionalidade original, mas filtrada de acordo com a máscara.

### Mascaramento Booleano por Operações Vetorizadas

O último bloco, `new_mask = array_3d % 2 == 0` seguido de `array_3d[new_mask]`, introduz o conceito de **operações vetorizadas (element-wise)** combinadas com mascaramento condicional.

* Quando uma expressão relacional (como >, <, ==) é aplicada a um arranjo (ndarray), o NumPy avalia essa condição elemento a elemento. O resultado gerado é um novo arranjo — com formato e dimensionalidade idênticos ao original — preenchido exclusivamente com valores booleanos (True ou False).


In [25]:
new_mask = array_3d % 2 == 0
new_mask

array([[[False,  True, False],
        [ True, False,  True],
        [False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True],
        [False,  True, False],
        [ True, False,  True]]])

A expressão` % 2 == 0` é avaliada elemento a elemento em toda a estrutura do array_3d. Em vez de retornar um único valor, o NumPy gera um novo arranjo booleano (new_mask) com o formato exato do arranjo original (2, 4, 3), preenchido com True onde a condição é satisfeita (números pares) e False caso contrário.

In [24]:
array_3d[new_mask]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

Quando esse arranjo booleano de dimensões correspondentes é passado como índice (`array_3d[new_mask]`), o NumPy extrai exclusivamente os elementos correspondentes a True. Devido à natureza irregular dos dados filtrados (a estrutura de grade multidimensional não pode ser garantida se os números pares estiverem dispersos de forma assimétrica), o NumPy, por padrão, "achata" o resultado, retornando um arranjo unidimensional (1D) contendo apenas os valores que satisfazem a condição matemática.